// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"context"
	"github.com/seregaa020292/ModularMonolith/internal/config"
	"github.com/seregaa020292/ModularMonolith/internal/config/logger"
	"github.com/seregaa020292/ModularMonolith/internal/config/pg"
	"github.com/seregaa020292/ModularMonolith/internal/fine/query"
	"github.com/seregaa020292/ModularMonolith/internal/fine/repository"
	"github.com/seregaa020292/ModularMonolith/internal/handlers/httprest"
	"github.com/seregaa020292/ModularMonolith/internal/infrastructure/server"
	"github.com/seregaa020292/ModularMonolith/internal/infrastructure/server/respond"
	"github.com/seregaa020292/ModularMonolith/internal/infrastructure/server/router"
	repository2 "github.com/seregaa020292/ModularMonolith/internal/notification/repository"
	repository3 "github.com/seregaa020292/ModularMonolith/internal/owner/repository"
	repository4 "github.com/seregaa020292/ModularMonolith/internal/payment/repository"
)

// Injectors from di.go:

// NewRegistry функция использует Google Wire для автоматической сборки зависимостей.
//
// В качестве параметров принимает контекст выполнения ctx и конфигурацию cfg.
// Возвращает указатель на Registry, функцию для очистки и ошибку, если таковая возникнет.
func New(ctx context.Context, cfg *config.Config) (*container, func(), error) {
	appConfig := cfg.App
	loggerConfig := cfg.Logger
	slogLogger := logger.New(loggerConfig)
	pgConfig := cfg.PG
	db, cleanup, err := pg.New(pgConfig)
	if err != nil {
		return nil, nil, err
	}
	fineRepo := repository.NewFineRepo(db)
	getListHandler := query.NewGetList(fineRepo)
	fineHandler := httprest.NewFineHandler(getListHandler)
	notificationRepo := repository2.NewNotificationRepo(db)
	notificationHandler := httprest.NewNotificationHandler(notificationRepo)
	ownerRepo := repository3.NewOwnerRepo(db)
	ownerHandler := httprest.NewOwnerHandler(ownerRepo)
	paymentRepo := repository4.NewPaymentRepo(db)
	paymentHandler := httprest.NewPaymentHandler(paymentRepo)
	vehicleHandler := httprest.NewVehicleHandler()
	openApiHandler := &httprest.OpenApiHandler{
		FineHandler:         fineHandler,
		NotificationHandler: notificationHandler,
		OwnerHandler:        ownerHandler,
		PaymentHandler:      paymentHandler,
		VehicleHandler:      vehicleHandler,
	}
	handle := respond.New()
	adminHandler := httprest.NewAdminHandler(handle)
	appApiHandler := &httprest.AppApiHandler{
		AdminHandler: adminHandler,
	}
	routerRouter := router.New(openApiHandler, appApiHandler, handle, slogLogger)
	v := provideServOptions()
	serverServer := server.New(appConfig, slogLogger, routerRouter, v...)
	diContainer := &container{
		Server: serverServer,
	}
	return diContainer, func() {
		cleanup()
	}, nil
}

// di.go:

type container struct {
	Server *server.Server
}

func provideServOptions() []server.Option {
	return nil
}
