//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Fines struct {
	ID          uuid.UUID `sql:"primary_key"`
	VehicleID   *uuid.UUID
	IssueDate   time.Time
	DueDate     time.Time
	Amount      float64
	Status      string
	Description *string
	CreatedAt   time.Time
	UpdatedAt   *time.Time
}
