//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Notifications struct {
	ID                 uuid.UUID `sql:"primary_key"`
	OwnerID            *uuid.UUID
	FineID             *uuid.UUID
	SentAt             *time.Time
	NotificationType   string
	NotificationStatus string
	CreatedAt          time.Time
	UpdatedAt          *time.Time
}
