//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"github.com/google/uuid"
	"time"
)

type Payments struct {
	ID            uuid.UUID `sql:"primary_key"`
	FineID        *uuid.UUID
	PaidDate      *time.Time
	Amount        float64
	PaymentMethod string
	CreatedAt     time.Time
	UpdatedAt     *time.Time
}
